/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsWorkflowRunIdRouteImport } from './routes/app.workflows.$workflowRunId'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiArtifactsUrlRouteImport } from './routes/api/artifacts/url'
import { Route as ApiGithubInstallStartRouteImport } from './routes/api/github/install/start'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsWorkflowRunIdRoute =
  AppWorkflowsWorkflowRunIdRouteImport.update({
    id: '/workflows/$workflowRunId',
    path: '/workflows/$workflowRunId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsUrlRoute = ApiArtifactsUrlRouteImport.update({
  id: '/api/artifacts/url',
  path: '/api/artifacts/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallStartRoute = ApiGithubInstallStartRouteImport.update({
  id: '/api/github/install/start',
  path: '/api/github/install/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/api/github/install/callback',
    path: '/api/github/install/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/artifacts/url': typeof ApiArtifactsUrlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/app/workflows/$workflowRunId': typeof AppWorkflowsWorkflowRunIdRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/artifacts/url': typeof ApiArtifactsUrlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/app/workflows/$workflowRunId': typeof AppWorkflowsWorkflowRunIdRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/artifacts/url': typeof ApiArtifactsUrlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/app/workflows/$workflowRunId': typeof AppWorkflowsWorkflowRunIdRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/artifacts/url'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/github/webhook'
    | '/app/workflows/$workflowRunId'
    | '/api/github/install/callback'
    | '/api/github/install/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/artifacts/url'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/github/webhook'
    | '/app/workflows/$workflowRunId'
    | '/api/github/install/callback'
    | '/api/github/install/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/artifacts/url'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/github/webhook'
    | '/app/workflows/$workflowRunId'
    | '/api/github/install/callback'
    | '/api/github/install/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiArtifactsUrlRoute: typeof ApiArtifactsUrlRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
  ApiGithubInstallStartRoute: typeof ApiGithubInstallStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/$workflowRunId': {
      id: '/app/workflows/$workflowRunId'
      path: '/workflows/$workflowRunId'
      fullPath: '/app/workflows/$workflowRunId'
      preLoaderRoute: typeof AppWorkflowsWorkflowRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/url': {
      id: '/api/artifacts/url'
      path: '/api/artifacts/url'
      fullPath: '/api/artifacts/url'
      preLoaderRoute: typeof ApiArtifactsUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/start': {
      id: '/api/github/install/start'
      path: '/api/github/install/start'
      fullPath: '/api/github/install/start'
      preLoaderRoute: typeof ApiGithubInstallStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/api/github/install/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppWorkflowsWorkflowRunIdRoute: typeof AppWorkflowsWorkflowRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkflowsWorkflowRunIdRoute: AppWorkflowsWorkflowRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiArtifactsUrlRoute: ApiArtifactsUrlRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
  ApiGithubInstallStartRoute: ApiGithubInstallStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
