import * as Config from 'effect/Config'

export const sourceControlRuntimeEnv = {
  CONVEX_URL: Config.string('CONVEX_URL'),
  VITE_CONVEX_URL: Config.string('VITE_CONVEX_URL'),
  PATCHPLANE_SYSTEM_INGESTION_SECRET: Config.redacted('PATCHPLANE_SYSTEM_INGESTION_SECRET'),
  PATCHPLANE_GITHUB_ALLOWED_REPOSITORIES: Config.string('PATCHPLANE_GITHUB_ALLOWED_REPOSITORIES'),
  PATCHPLANE_GITHUB_WORKSPACE_ID: Config.string('PATCHPLANE_GITHUB_WORKSPACE_ID').pipe(Config.withDefault('')),
  PATCHPLANE_WORKOS_ORGANIZATION_ID: Config.string('PATCHPLANE_WORKOS_ORGANIZATION_ID'),
  GITHUB_APP_ID: Config.string('GITHUB_APP_ID'),
  GITHUB_PRIVATE_KEY: Config.redacted('GITHUB_PRIVATE_KEY'),
  GITHUB_WEBHOOK_SECRET: Config.redacted('GITHUB_WEBHOOK_SECRET'),
  DAYTONA_API_KEY: Config.redacted('DAYTONA_API_KEY'),
  OPENAI_API_KEY: Config.redacted('OPENAI_API_KEY'),
  PATCHPLANE_EVIDENCE_TEST_REPORT_COMMAND: Config.string('PATCHPLANE_EVIDENCE_TEST_REPORT_COMMAND').pipe(Config.withDefault('')),
  PATCHPLANE_EVIDENCE_BROWSER_SCREENSHOT_COMMAND: Config.string('PATCHPLANE_EVIDENCE_BROWSER_SCREENSHOT_COMMAND').pipe(Config.withDefault('')),
  SENTRY_DSN: Config.string('SENTRY_DSN'),
} as const

export const clientRuntimeEnv = {
  CONVEX_URL: Config.string('CONVEX_URL'),
  VITE_CONVEX_URL: Config.string('VITE_CONVEX_URL'),
  VITE_WORKOS_CLIENT_ID: Config.string('VITE_WORKOS_CLIENT_ID'),
  VITE_WORKOS_REDIRECT_URI: Config.string('VITE_WORKOS_REDIRECT_URI'),
  WORKOS_API_KEY: Config.redacted('WORKOS_API_KEY'),
  WORKOS_CLIENT_ID: Config.string('WORKOS_CLIENT_ID'),
  WORKOS_COOKIE_PASSWORD: Config.redacted('WORKOS_COOKIE_PASSWORD'),
  WORKOS_REDIRECT_URI: Config.string('WORKOS_REDIRECT_URI'),
  PATCHPLANE_WORKOS_ORGANIZATION_ID: Config.string('PATCHPLANE_WORKOS_ORGANIZATION_ID'),
  PATCHPLANE_GITHUB_APP_INSTALL_URL: Config.string('PATCHPLANE_GITHUB_APP_INSTALL_URL'),
  PATCHPLANE_GITHUB_APP_SLUG: Config.string('PATCHPLANE_GITHUB_APP_SLUG'),
  SENTRY_DSN: Config.string('SENTRY_DSN'),
} as const
