import * as Config from 'effect/Config'
import * as Redacted from 'effect/Redacted'

const optionalRedacted = (name: string) =>
  Config.redacted(name).pipe(Config.withDefault(Redacted.make('')))

export const sourceControlRuntimeEnv = {
  CONVEX_URL: Config.string('CONVEX_URL'),
  VITE_CONVEX_URL: Config.string('VITE_CONVEX_URL'),
  PATCHPLANE_SYSTEM_INGESTION_SECRET: Config.redacted(
    'PATCHPLANE_SYSTEM_INGESTION_SECRET',
  ),
  PATCHPLANE_GITHUB_ALLOWED_REPOSITORIES: Config.string(
    'PATCHPLANE_GITHUB_ALLOWED_REPOSITORIES',
  ),
  PATCHPLANE_GITHUB_WORKSPACE_ID: Config.string(
    'PATCHPLANE_GITHUB_WORKSPACE_ID',
  ).pipe(Config.withDefault('')),
  PATCHPLANE_WORKOS_ORGANIZATION_ID: Config.string(
    'PATCHPLANE_WORKOS_ORGANIZATION_ID',
  ),
  GITHUB_APP_ID: Config.string('GITHUB_APP_ID'),
  GITHUB_PRIVATE_KEY: Config.redacted('GITHUB_PRIVATE_KEY'),
  GITHUB_WEBHOOK_SECRET: Config.redacted('GITHUB_WEBHOOK_SECRET'),
  DAYTONA_API_KEY: Config.redacted('DAYTONA_API_KEY'),
  OPENAI_API_KEY: Config.redacted('OPENAI_API_KEY'),
  CLOUDFLARE_SENTRY_DSN: optionalRedacted('CLOUDFLARE_SENTRY_DSN'),
  PATCHPLANE_EVIDENCE_TEST_REPORT_COMMAND: Config.string(
    'PATCHPLANE_EVIDENCE_TEST_REPORT_COMMAND',
  ).pipe(Config.withDefault('')),
  PATCHPLANE_EVIDENCE_TEST_PLATFORM: Config.string(
    'PATCHPLANE_EVIDENCE_TEST_PLATFORM',
  ).pipe(Config.withDefault('linux')),
  PATCHPLANE_EVIDENCE_BROWSER_SCREENSHOT_COMMAND: Config.string(
    'PATCHPLANE_EVIDENCE_BROWSER_SCREENSHOT_COMMAND',
  ).pipe(Config.withDefault('')),
  PATCHPLANE_WORKSPACE_VERIFICATION_POLICY_JSON: Config.string(
    'PATCHPLANE_WORKSPACE_VERIFICATION_POLICY_JSON',
  ).pipe(Config.withDefault('')),
  PATCHPLANE_BASE_REPOSITORY_VERIFICATION_POLICY_JSON: Config.string(
    'PATCHPLANE_BASE_REPOSITORY_VERIFICATION_POLICY_JSON',
  ).pipe(Config.withDefault('')),
} as const

export const clientRuntimeEnv = {
  CLOUDFLARE_SENTRY_DSN: optionalRedacted('CLOUDFLARE_SENTRY_DSN'),
  CONVEX_URL: Config.string('CONVEX_URL'),
  VITE_CONVEX_URL: Config.string('VITE_CONVEX_URL'),
  VITE_SENTRY_DSN: Config.string('TANSTACK_SENTRY_DSN'),
  VITE_WORKOS_CLIENT_ID: Config.string('VITE_WORKOS_CLIENT_ID'),
  VITE_WORKOS_REDIRECT_URI: Config.string('VITE_WORKOS_REDIRECT_URI'),
  WORKOS_API_KEY: Config.redacted('WORKOS_API_KEY'),
  WORKOS_CLIENT_ID: Config.string('WORKOS_CLIENT_ID'),
  WORKOS_COOKIE_PASSWORD: Config.redacted('WORKOS_COOKIE_PASSWORD'),
  WORKOS_REDIRECT_URI: Config.string('WORKOS_REDIRECT_URI'),
  PATCHPLANE_WORKOS_ORGANIZATION_ID: Config.string(
    'PATCHPLANE_WORKOS_ORGANIZATION_ID',
  ),
  PATCHPLANE_GITHUB_APP_INSTALL_URL: Config.string(
    'PATCHPLANE_GITHUB_APP_INSTALL_URL',
  ),
  PATCHPLANE_GITHUB_APP_SLUG: Config.string('PATCHPLANE_GITHUB_APP_SLUG'),
} as const
